config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  
  get "redesign" => "redesign#index"

  root to: "home#index"
  get "legal" => "home#legal"
  get 'developer' => 'home#developer'
  post 'contact_us' => 'home#contact_us'

  # Legacy implementation used POST /oauth/authorize for both the user facing
  # authorization screen and the API endpoint to request a token ... so, we have
  # to support it. Set this route before the `use_doorkeeper` call so that this
  # route takes precedence over the other doorkeeper routes.
  post '/oauth/authorize' => 'doorkeeper/tokens#create', constraints: ->(req) {
    req.params['grant_type'] == 'authorization_code'
  }

  use_doorkeeper do
    skip_controllers :applications
    controllers authorizations: 'oauth/authorizations',
                authorized_applications: 'oauth/authorized_applications'
  end

  get 'authorizations' => 'oauth/authorized_applications#index'

  # Pull this out of the `use_doorkeeper` block so that we can put it at the
  # root level.
  # resources :applications, only: %w(new create show edit update destroy), as: 'oauth_applications'
  resources :applications, as: 'oauth_applications'

  post 'new_api_key' => 'applications#new_api_key'
  post 'make_public' => 'applications#make_public'

  devise_for :users,
    controllers: {
      omniauth_callbacks: "omniauth_callbacks" ,
      sessions: "sessions"
    }

  devise_scope :user do
    resource :user, only: [:update]
    get 'users/sign_in/:token_id' => 'sessions#show', as: 'user_session_token'

    namespace :users do
      namespace :factors do
        resource :sms
      end
    end
  end

  resource :mobile_recovery
  get 'mobile_recovery/cancel' => 'mobile_recoveries#cancel'
  get 'mobile_recovery/welcome' => 'mobile_recoveries#welcome'

  get 'settings/notifications' => 'notification_settings#index'
  post 'settings/notifications' => 'notification_settings#update'

  get 'unsubscribe/:delivery_method', to: 'unsubscribe#unsubscribe', as: 'unsubscribe'

  resource :profile, only: [:show, :edit, :additional, :update, :destroy] do
    get :additional
  end

  get 'settings/account_settings' => 'settings#account_settings'

  get 'admin' => 'admin#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1, as: 'v1' do
      resource :profile, only: [:show]
      resources :notifications, only: [:create]
      resources :tasks do
        resources :task_items
      end

      get 'tokeninfo', to: '/doorkeeper/token_info#show'
    end

    # For legacy reasons, we translate any API request without a version
    # in the path as a version 1 request.
    # e.g. `/api/STUFF` -> `/api/v1/STUFF`
    # Alas, I haven't found a better way of doing that translation than route
    # duplication. -- Yoz
    scope module: 'v1' do
      resource :profile, only: [:show]
      resources :notifications, only: [:create]
      resources :tasks do
        resources :task_items
      end
    end
  end

  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unprocessable_entity'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  protected

  def clear_return_to
    key = stored_location_key_for(:user)
    session.delete(key)
  end

  private

  # Considering this is followed by a test that the URL matches registered domain,
  # I decided to make this simpler since prior version was rejecting valid URLs
  def valid_url?(uri)
    parsed = URI.parse(uri)
    return (parsed.scheme == 'http' || parsed.scheme == 'https')
  rescue URI::InvalidURIError
    false
  end

  def member_subdomain?(url_list, url)
    url_list.any? do |list_url|
      list_host = URI.parse(list_url).host
      url_host = URI.parse(url).host
      list_host == url_host || url_host.ends_with?(".#{list_host}")
    end
  end

  def after_sign_in_path_for(resource_or_scope)
    if current_user.sign_in_count == 1 && session[:user_return_to] !~ /oauth\/authorize/
      session[:two_factor_return_to] = mobile_recovery_welcome_path
      new_mobile_recovery_path
    else
      require_two_factor! if current_user.two_factor_required
      stored_location_for(resource_or_scope) || profile_path
    end
  end

  # Overriding Devise method to allow for redirect_url
  def after_sign_out_path_for(resource_or_scope)
    url = params[:continue]
    if !url.blank? &&
       valid_url?(url) &&
       @logged_out_user &&
       member_subdomain?(
         Doorkeeper::Application.authorized_for(@logged_out_user).map(&:url).compact,
         url)
      return url
    end
    super(resource_or_scope)
  end

  def authenticate_user!(opts={})
    super
    require_two_factor! if current_user.two_factor_required
    current_user
  end

  def require_owner_or_admin!
    require_owner!
  rescue SimpleRole::AccessDenied => e
    require_admin!
  end

  def require_owner!
    authenticate_user!
    current_user.has_role?(:owner, resource) or raise SimpleRole::AccessDenied
  end

  def require_admin!
    authenticate_user!
    if current_user.has_role?(:admin)
      require_two_factor!
      UserAction.admin_action.create(data: params)
      return true
    else
      raise SimpleRole::AccessDenied
    end
  end

  def require_two_factor!
    warden.authenticate!(scope: :two_factor)
  end

  def two_factor_configured?
    current_user.mobile_number.present?
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_filter :authenticate_user!

  before_filter :set_application, only: [:show, :edit, :update, :destroy, :new_api_key, :make_public]
  before_filter :require_owner_or_admin!, only: [:show, :edit, :update, :destroy, :new_api_key, :make_public]

  layout 'dashboard'

  def new
    build_application
  end

  def create
    build_application
    update_application

    if @application.errors.empty? && @application.save
      current_user.grant_role!(:owner, @application)

      message = I18n.t('new_application')
      flash[:notice] = render_to_string partial: 'applications/flash',
                                        locals: { application: @application, message: message }
      redirect_to authorizations_path
    else
      render :new
    end
  end

  def update
    update_application

    if @application.errors.empty? && @application.save
      flash[:notice] = I18n.t(:notice, scope: [:doorkeeper, :flash, :applications, :update])
      if params[:return_to]
        redirect_to params[:return_to]
      else
        redirect_to authorizations_path
      end
    else
      render :edit
    end
  end

  def destroy
    flash[:notice] = I18n.t(:notice, scope: [:doorkeeper, :flash, :applications, :destroy]) if @application.destroy
    redirect_to authorizations_path
  end

  # TODO: roll this into update
  def new_api_key
    @application = Doorkeeper::Application.find(params[:id])
    @application.secret = Doorkeeper::OAuth::Helpers::UniqueToken.generate
    @application.save
    message = I18n.t('new_api_key')
    flash[:notice] = render_to_string partial: 'applications/flash',
                                      locals: { message: message }
    redirect_to authorizations_path
  end

  # TODO: roll this into update
  def make_public
    @application = Doorkeeper::Application.find(params[:id])
    @application.request_public(current_user)
    redirect_to authorizations_path, notice: I18n.t('app_status.requested_public')
  end

  private

  def resource
    @application
  end

  def build_application
    @application = Doorkeeper::Application.new
  end

  def set_application
    @application = Doorkeeper::Application.find(params[:id])
  end

  def update_application
    @application.attributes = application_params
  end

  def allowed_application_params
    params = [
      :name, :description, :short_description, :custom_text, :url,
      :logo_url, :owner_emails, :developer_emails, :scopes, :redirect_uri,
      :federal_agency, :organization, :terms_of_service_accepted, :tos_link,
      :privacy_policy_link, :scopes
    ]
    if current_user.has_role?(:admin)
      params << :public
    end

    return params
  end

  # How the form gets away with using scope
  def application_params
    if params.has_key?(:scope)
      params[:application][:scopes] = params[:scope].join(' ')
    end

    params.require(:application).permit(*allowed_application_params)
  end
end

app/controllers/oauth/applications_controller.rb
class Oauth::ApplicationsController < Doorkeeper::ApplicationsController
  before_filter :authenticate_user!
  layout 'dashboard'

  def index
    super
    @authorizations = Doorkeeper::AccessToken.where(
      resource_owner_id: current_user.id, revoked_at: nil)
    @applications = current_user.oauth_applications
  end

  def create
    @application = Doorkeeper::Application.new(application_params)
    @application.owner = current_user
    if @application.save
      message = I18n.t('new_application')
      flash[:notice] = render_to_string partial: 'doorkeeper/applications/flash',
                                        locals: { application: @application, message: message }
      redirect_to oauth_applications_path
    else
      render :new
    end
  end

  def update
    if @application.update_attributes(application_params)
      flash[:notice] = I18n.t(:notice, scope: [:doorkeeper, :flash, :applications, :update])
      redirect_to oauth_applications_path
    else
      render :edit
    end
  end

  def new_api_key
    @application = Doorkeeper::Application.find(params[:id])
    @application.secret = Doorkeeper::OAuth::Helpers::UniqueToken.generate
    @application.save
    message = I18n.t('new_api_key')
    flash[:notice] = render_to_string partial: 'doorkeeper/applications/flash',
                                      locals: { message: message }
    redirect_to oauth_applications_path
  end

  def make_public
    @application = Doorkeeper::Application.find(params[:id])
    @application.requested_public_at = DateTime.now
    @application.save
    redirect_to oauth_applications_path, notice: I18n.t('app_status.requested_public') 
  end

  private

  def application_params
    app_params = params.require(:application).permit(:name, :description, :short_description, :custom_text, :url, :image, :scopes, :redirect_uri)
    app_params[:scopes] = params[:scope] ? params[:scope].join(' ') : []
    app_params
  end
end

app/helpers/application_helper.rb
# ApplicationHelper
module ApplicationHelper
  def standard_flash(msg)
    bootstrap_key_mapping =
    {
      'alert' => 'warning',
      'error' => 'danger',
      'notice' => 'info'
    }
    bootstrap_key_mapping[msg] || msg
  end

  def bs_button_to(text, action, options = {})
    form_tag action do
      button_tag({ type: 'submit' }.merge(options)) do
        text
      end
    end
  end

  def yes_or_no(value)
    return '' if value.nil?
    value ? 'Yes' : 'No'
  end

  def suffix_options
    [
      ['Jr.', 'Jr.'],
      ['Sr.', 'Sr.'],
      ['II', 'II'],
      ['III', 'III'],
      ['IV', 'IV']
    ]
  end

  def title_options
    [
      ['Mr.', 'Mr.'],
      ['Mrs.', 'Mrs.'],
      ['Miss', 'Miss'],
      ['Ms.', 'Ms.']
    ]
  end

  def us_state_options
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

  def gender_options
    [
      ['Male', 'male'],
      ['Female', 'female']
    ]
  end

  def marital_status_options
    [
      ['Single', 'single'],
      ['Married', 'married'],
      ['Divorced', 'divorced'],
      ['Domestic Partnership', 'domestic_partnership'],
      ['Widowed', 'widowed']
    ]
  end

  def yes_no_options
    [['Yes', true], ['No', false]]
  end

  def yes_no_options_for_select(value)
    options_for_select(yes_no_options, value)
  end

  def not_me_path
    '?' + Rack::Utils.build_query(request.query_parameters.merge(logout: true))
  end

  def application_filters
    [
      ['all', 'All'],
      ['pending-approval', 'Pending Approval']
    ]
  end

  def application_filter_tabs
    filter = params[:filter] || 'all'
    content_tag(:ul, class: 'nav navbar-nav nav-tabs') do
      safe_join(application_filters.collect do |item|
        content_tag(:li, role: 'presentation', class: item.first == filter ? 'active' : '') do
          link_to(item.second, "?filter=#{item.first}")
        end
      end)
    end
  end
end

app/views/applications/_flash.html.erb
<h4><%= message %> Please save the below information in safe place.</h4>
<div class='row'>
	<div class='col-md-3'> Consumer Public Key </div>
	<div class='col-md-3'> <%= @application.uid %> </div>
</div>
<div class='row'>
	<div class='col-md-3'> Consumer Secret Key  </div>
	<div class='col-md-3' id='secret-key'> <%= @application.secret %> </div>
</div>

app/views/applications/_form.html.erb
<%= form_for [:oauth, application], id: 'new_application', html: {multipart: true, class: 'form', role: 'form'} do |f| %>
  <% if application.errors.any? %>
    <div class="alert alert-danger" data-alert><p>Whoops! Check your form for possible errors</p></div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:name].present?}" do %>
    <div class="form-group">
      <%= f.label :name, class: 'control-label', for: 'application_name' %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= errors_for application, :name %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:description].present?}" do %>
    <div class="form-group">
      <%= f.label :description, class: 'control-label', for: 'application_description' %>
      <%= f.text_area(:description, size:'50x5', class: 'form-control', maxlength: 255)%>
      <%= errors_for application, :description %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:short_description].present?}" do %>
    <div class="form-group">
      <%= f.label :short_description, class: 'control-label', for: 'application_short_description' %>
      <%= f.text_field :short_description, class: 'form-control' %>
      <%= errors_for application, :short_description %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:organization].present?}" do %>
  <div class="form-group">
    <%= f.label :organization, class: 'control-label', for: 'application_organization' %>
    <%= f.text_field :organization, class: 'form-control' %>
    <%= errors_for application, :organization %>
  </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:federal_agency_tos].present?}" do %>
    <div class="checkbox">
      <label >
        <%= f.check_box :federal_agency %>
        <%= t('application.federal_agency') %>
      </label>
    </div>
    <%= errors_for application, :federal_agency %>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:terms_of_service_accepted].present?}#{' collapse' if !application.federal_agency}" do %>
  <div class="checkbox">
    <label>
      <%= f.check_box :terms_of_service_accepted %>
      <%= t('application.federal_agency_tos', tos_link: legal_path(anchor: 'terms-of-service')).html_safe %>
    </label>
  </div>
  <%= errors_for application, :terms_of_service_accepted %>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:url].present?}" do %>
    <div class="form-group">
      <%= f.label :url, class: 'control-label', for: 'application_url' %>
      <%= f.text_field :url, class: 'form-control' %>
      <%= errors_for application, :url %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:redirect_uri].present?}" do %>
    <div class="form-group">
      <%= f.label :redirect_uri, class: 'control-label', for: 'application_redirect_uri' %>
      <%= f.text_field :redirect_uri, class: 'form-control' %>
      <%= errors_for application, :redirect_uri %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:logo_url].present?}" do %>
    <div class="form-group">
      <%= f.label :logo_url, class: ' control-label', for: 'application_logo_url' %>
      <span class="help-block">
        <%= t('application.logo_url_hint') %>
      </span>
      <%= f.text_field :logo_url, class: 'form-control' %>
      <%= errors_for application, :logo_url %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:tos_link].present?}" do %>
    <div class="form-group">
      <%= f.label :tos_link, class: 'control-label', for: 'application_tos_link' %>
      <%= f.text_field :tos_link, class: 'form-control' %>
      <%= errors_for application, :tos_link %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:privacy_policy_link].present?}" do %>
    <div class="form-group">
      <%= f.label :privacy_policy_link, class: 'control-label', for: 'application_privacy_policy_link' %>
      <%= f.text_field :privacy_policy_link, class: 'form-control' %>
      <%= errors_for application, :privacy_policy_link %>
    </div>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:custom_text].present?}" do %>
    <div class="form-group">
      <%= f.label :custom_text, class: 'control-label', for: 'application_custom_text' %>
      <%= f.text_field :custom_text, class: 'form-control' %>
      <%= errors_for application, :custom_text %>
    </div>
  <% end %>

  <% if current_user.has_role?(:admin) %>
    <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:public].present?}" do %>
      <div class="form-group">
        <%= f.label :public, class: 'control-label', for: 'application_url' %>
        <%= f.select :public, [['Public', true], ['Private', false]], {}, class: 'form-control' %>
        <%= errors_for application, :public %>
      </div>
    <% end %>
  <% end %>

  <%= content_tag :div, class: "form-group#{' has-error' if application.errors[:developer_emails].present?}" do %>
    <div class="form-group">
      <%= f.label :developer_emails, class: 'control-label', for: 'developer_emails' %>
      <%= f.text_field :developer_emails, class: 'form-control tokenize' %>
      <%= errors_for application, :developer_emails %>
    </div>
  <% end %>

  <% if application.errors[:scopes].present? %>
    <%= content_tag :div, class: "form-group" do %>
      <div class="alert alert-danger">
        You must select at least one scope.
      </div>
    <% end %>
  <% end %>

  <%= content_tag :div, class: "form-group" do %>
    <h2>
      Select the API Scopes that your Application will use
   </h2>
  <% end %>

  <%= render 'scope_list', application: application, selected_scopes: application.scopes %>

  <div>
    <div class="col-md-8 col-sm-8">
      <%= f.submit 'Save Application', class: "btn btn-primary width-100" %>
    </div>
    <div class="col-md-4 col-sm-4">
      <%= link_to t(:cancel), authorizations_path, :class => 'btn btn-default width-100' %>
    </div>
  </div>
<% end %>

app/views/applications/_scope_list.html.erb
<% scopes_by_group do |group, group_scopes| %>
  <%- if group_scopes.present? -%>
    <%= content_tag :div, class: "form-group" do %>
        <div class="form-group scope">
          <%= t("scope_groups.#{group}.description") %>
          <% group_scopes.each do |scope| %>
            <div class="scope-option">
              <%= scope_check_box_tag scope, selected_scopes.member?(scope) %>
              <%= scope_field_label(scope) %>
            </div>
          <% end %>
        </div>
    <% end %>
  <% end %>
<% end %>

app/views/applications/edit.html.erb
<div class="row aglio app-settings">
  <div class="col-md-3">
    <%= render 'profiles/nav'%>
  </div>
  <div class="col-md-9">
    <h1>Edit Application</h1>

    <%= render 'form', application: @application %>
  </div>
</div>

app/views/applications/new.html.erb
<div class="row aglio app-settings">
  <div class="col-md-3">
    <%= render 'profiles/nav'%>
  </div>
  <div class="col-md-9">
    <h1>New Application</h1>
    <%= render 'form', application: @application %>
  </div>
</div>

app/views/applications/show.html.erb
<div class="page-header">
  <h1>Application: <%= @application.name %></h1>
</div>

<div class="row">
  <div class="col-md-8">
    <h4>Application Id:</h4>

    <p><code id="application_id"><%= @application.uid %></code></p>

    <h4>Secret:</h4>

    <p><code id="secret"><%= @application.secret %></code></p>


    <h4>Description</h4>
      <p><code><%= @application.description %></code></p>

    <h4>Short Description</h4>
      <p><code><%= @application.short_description %></code></p>

    <h4>Image</h4>
    <p>
      <%= image_tag @application.logo_url %>
    </p>

    <h4>Custom Text</h4>
      <p><code><%= @application.custom_text %></code></p>

    <h4>Scopes:</h4>

    <% @application.scopes.each do |scope| %>
      <p><code><%= scope %></code></p>
    <% end %>

    <h4>URL</h4>
      <p><code><%= @application.url %></code></p>

    <h4>Callback urls:</h4>

    <table>
      <% @application.redirect_uri.split.each do |uri| %>
        <tr>
          <td>
            <code><%= uri %></code>
          </td>
          <td>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="col-md-4">
    <h3>Actions</h3>

    <p><%= link_to 'Edit', edit_oauth_application_path(@application), class: 'btn btn-primary' %></p>

    <p><%= render 'delete_form', application: @application, submit_btn_css: 'btn btn-danger' %></p>
  </div>
</div>