config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  
  get "redesign" => "redesign#index"

  root to: "home#index"
  get "legal" => "home#legal"
  get 'developer' => 'home#developer'
  post 'contact_us' => 'home#contact_us'

  # Legacy implementation used POST /oauth/authorize for both the user facing
  # authorization screen and the API endpoint to request a token ... so, we have
  # to support it. Set this route before the `use_doorkeeper` call so that this
  # route takes precedence over the other doorkeeper routes.
  post '/oauth/authorize' => 'doorkeeper/tokens#create', constraints: ->(req) {
    req.params['grant_type'] == 'authorization_code'
  }

  use_doorkeeper do
    skip_controllers :applications
    controllers authorizations: 'oauth/authorizations',
                authorized_applications: 'oauth/authorized_applications'
  end

  get 'authorizations' => 'oauth/authorized_applications#index'

  # Pull this out of the `use_doorkeeper` block so that we can put it at the
  # root level.
  # resources :applications, only: %w(new create show edit update destroy), as: 'oauth_applications'
  resources :applications, as: 'oauth_applications'

  post 'new_api_key' => 'applications#new_api_key'
  post 'make_public' => 'applications#make_public'

  devise_for :users,
    controllers: {
      omniauth_callbacks: "omniauth_callbacks" ,
      sessions: "sessions"
    }

  devise_scope :user do
    resource :user, only: [:update]
    get 'users/sign_in/:token_id' => 'sessions#show', as: 'user_session_token'

    namespace :users do
      namespace :factors do
        resource :sms
      end
    end
  end

  resource :mobile_recovery
  get 'mobile_recovery/cancel' => 'mobile_recoveries#cancel'
  get 'mobile_recovery/welcome' => 'mobile_recoveries#welcome'

  get 'settings/notifications' => 'notification_settings#index'
  post 'settings/notifications' => 'notification_settings#update'

  get 'unsubscribe/:delivery_method', to: 'unsubscribe#unsubscribe', as: 'unsubscribe'

  resource :profile, only: [:show, :edit, :additional, :update, :destroy] do
    get :additional
  end

  get 'settings/account_settings' => 'settings#account_settings'

  get 'admin' => 'admin#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1, as: 'v1' do
      resource :profile, only: [:show]
      resources :notifications, only: [:create]
      resources :tasks do
        resources :task_items
      end

      get 'tokeninfo', to: '/doorkeeper/token_info#show'
    end

    # For legacy reasons, we translate any API request without a version
    # in the path as a version 1 request.
    # e.g. `/api/STUFF` -> `/api/v1/STUFF`
    # Alas, I haven't found a better way of doing that translation than route
    # duplication. -- Yoz
    scope module: 'v1' do
      resource :profile, only: [:show]
      resources :notifications, only: [:create]
      resources :tasks do
        resources :task_items
      end
    end
  end

  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unprocessable_entity'
end

app/views/admin/index.html.erb
<div class="row aglio app-settings">
  <div class="col-md-3">
    <%= render 'profiles/nav'%>
  </div>
  <div class="col-md-9">
    <h1>
      Applications
    </h1>

    <nav class="nav nav-tabs">
      <%= application_filter_tabs %>

      <%= form_for(:search, method: "get", html: {role: "search", class: "navbar-form navbar-right"}) do |f| %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
        </div>
        <%= submit_tag("Submit", class: "btn btn-default") %>
      <% end %>
    </nav>

    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Owner</th>
        <th>Status</th>
        <th>Users</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% if @applications.blank? %>
        <tr>
          <td colspan="3">
            there are no applications matching this criteria
          </td>
        </tr>
      <% end %>
      <% @applications.each do |application| %>
        <tr id="application_<%= application.id %>">
          <td><%= link_to application.name, edit_oauth_application_path(application) %></td>
          <td><%= application.owner.email %></td>
          <td><%= app_status(application) %></td>
          <td><%= application.number_of_authorizations %></td>
          <td>
            <%= link_to 'Edit Application', edit_oauth_application_path(application), class: 'btn btn-link' %>
            <%= form_for application, url: oauth_application_path(application) do |f| %>
              <%= hidden_field_tag(:return_to, admin_path(filter: params[:filter], page: params[:page])) %>
              <%= f.hidden_field(:public, value: !application.public) %>
              <%= f.submit "Make #{application.public ? 'Private' : 'Public'}", class: 'btn btn-link' %>
            <% end %>
            <%= render 'doorkeeper/authorized_applications/delete_form', application: application %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <%= will_paginate @applications %>
  </div>
</div>