config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  
  get "redesign" => "redesign#index"

  root to: "home#index"
  get "legal" => "home#legal"
  get 'developer' => 'home#developer'
  post 'contact_us' => 'home#contact_us'

  # Legacy implementation used POST /oauth/authorize for both the user facing
  # authorization screen and the API endpoint to request a token ... so, we have
  # to support it. Set this route before the `use_doorkeeper` call so that this
  # route takes precedence over the other doorkeeper routes.
  post '/oauth/authorize' => 'doorkeeper/tokens#create', constraints: ->(req) {
    req.params['grant_type'] == 'authorization_code'
  }

  use_doorkeeper do
    skip_controllers :applications
    controllers authorizations: 'oauth/authorizations',
                authorized_applications: 'oauth/authorized_applications'
  end

  get 'authorizations' => 'oauth/authorized_applications#index'

  # Pull this out of the `use_doorkeeper` block so that we can put it at the
  # root level.
  # resources :applications, only: %w(new create show edit update destroy), as: 'oauth_applications'
  resources :applications, as: 'oauth_applications'

  post 'new_api_key' => 'applications#new_api_key'
  post 'make_public' => 'applications#make_public'

  devise_for :users,
    controllers: {
      omniauth_callbacks: "omniauth_callbacks" ,
      sessions: "sessions"
    }

  devise_scope :user do
    resource :user, only: [:update]
    get 'users/sign_in/:token_id' => 'sessions#show', as: 'user_session_token'

    namespace :users do
      namespace :factors do
        resource :sms
      end
    end
  end

  resource :mobile_recovery
  get 'mobile_recovery/cancel' => 'mobile_recoveries#cancel'
  get 'mobile_recovery/welcome' => 'mobile_recoveries#welcome'

  get 'settings/notifications' => 'notification_settings#index'
  post 'settings/notifications' => 'notification_settings#update'

  get 'unsubscribe/:delivery_method', to: 'unsubscribe#unsubscribe', as: 'unsubscribe'

  resource :profile, only: [:show, :edit, :additional, :update, :destroy] do
    get :additional
  end

  get 'settings/account_settings' => 'settings#account_settings'

  get 'admin' => 'admin#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1, as: 'v1' do
      resource :profile, only: [:show]
      resources :notifications, only: [:create]
      resources :tasks do
        resources :task_items
      end

      get 'tokeninfo', to: '/doorkeeper/token_info#show'
    end

    # For legacy reasons, we translate any API request without a version
    # in the path as a version 1 request.
    # e.g. `/api/STUFF` -> `/api/v1/STUFF`
    # Alas, I haven't found a better way of doing that translation than route
    # duplication. -- Yoz
    scope module: 'v1' do
      resource :profile, only: [:show]
      resources :notifications, only: [:create]
      resources :tasks do
        resources :task_items
      end
    end
  end

  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unprocessable_entity'
end

app/views/marketing/_contact.html.erb
<section class="marketing" id="contact">
  <div class="top-border-blue">
    <div class="container">
      <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
          <h1 class="text-center">
            Still have questions? Drop us a line.
          </h1>
          <div class="contact-flash alert alert-warning hidden">
             <a href="#" data-dismiss="alert" class="close">×</a>
             <div class="message"></div>
          </div>
          <%= form_for :contact_us, url: contact_us_path(format: :json), html: { id: 'contact-form', role: "form" } do |f| %>
            <div class="form-group">
              <%= f.label 'Message:' %>
              <%= f.text_area :message, class: 'form-control', rows: 8, placeholder: 'How can we help you?' %>
            </div>
            <div class="form-group">
              <%= f.label 'From:' %>
              <%= f.text_field :from, class: 'form-control', placeholder: 'What is your name?' %>
            </div>
            <div class="form-group">
              <%= f.label 'Return Email:' %>
              <%= f.text_field :return_email, class: 'form-control', placeholder: 'What is your email address?' %>
            </div>
            <%= f.submit 'Send Us Your Message', id: 'contact_submit', 'data-loading-text' => "Sending your message...", class: 'btn btn-primary width-100' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/marketing/_for_agencies.html.erb
<section class="marketing" id="for-agencies"><a name="agencies"></a>
  <div class="top-border bottom-border bg-gray">
    <div class="container">
      <div class="row">
        <div class="col-md-12 logo">
          <%= image_tag "myusa-logo.png", :alt => 'MyUSA Logo', :width => 175, :height => 50, :class => 'vertical-bottom' %>
          <span class="for-agencies">
            &nbsp;for Agencies
          </span>
        </div>
      </div>
      <div class="row bottom-border">
        <div class="col-xs-offset-1 col-xs-10 col-sm-offset-0 col-sm-4 col-md-4">
          <div class="row">
            <div class="col-md-12 text-center">
              <i class="fa fa-6x icon-id-badge blue-dark"></i>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <h2 class="text-center">
                Simple registration, <br> instant authentication
              </h2>
              <p class="text-justify">
                MyUSA handles authentication, profile management, and privacy needs,
                letting users navigate government sites with ease.
              </p>
            </div>
          </div>
        </div>
        <div class="col-xs-offset-1 col-xs-10 col-sm-offset-0 col-sm-4 col-md-4">
          <div class="row">
            <div class="col-md-12 text-center">
              <i class="fa fa-6x icon-map blue-dark"></i>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <h2 class="text-center">
                Guide people to <br> what matters
              </h2>
              <p class="text-justify">
                Knowing more about your users lets you provide them the most relevant
                content, improving their experience. You’ll reduce support requests, too.

              </p>
            </div>
          </div>
        </div>
        <div class="col-xs-offset-1 col-xs-10 col-sm-offset-0 col-sm-4 col-md-4">
          <div class="row">
            <div class="col-md-12 text-center">
              <i class="fa fa-6x icon-paper-airplane blue-dark"></i>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <h2 class="text-center">
                No contracts, <br> No upfront costs
              </h2>
              <p class="text-justify">
                Provided as a free service from the General Services Administration,
                MyUSA offers you registration and log in, account management,
                and other building blocks for your agency needs.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12 text-center">
          <h2>
            Still have questions?
          </h2>
          <%= link_to 'Contact Us', '#contact' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/marketing/_for_developers.html.erb
<section class="marketing" id="for-developers">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="text-center">
          Simplified registration and account management start here
        </h1>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4 col-md-4 text-center numbered-step">
        <div>
          <span class="fa-stack fa-3x">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-stack-1x fa-inverse">1</i>
          </span>
        </div>
        <h2>
          Sign up for MyUSA
        </h2>
        <p>
          Create your MyUSA account or ask a representative from your agency to create an account.
        </p>
        <p>
          <%= link_to "Get Started", new_user_session_path, :target => "_new", :class => "btn btn-primary width-80" %>
        </p>
      </div>
      <div class="col-sm-4 col-md-4 text-center numbered-step">
        <div>
          <span class="fa-stack fa-3x">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-stack-1x fa-inverse">2</i>
          </span>
        </div>
        <h2>
          Register your application
        </h2>
        <p>
          Registering your application with MyUSA is simple.
        </p>
        <p>
          <%= link_to "Learn How", new_oauth_application_path, :target => "_new", :class => "btn btn-primary width-80" %>
        </p>
      </div>
      <div class="col-sm-4 col-md-4 text-center numbered-step">
        <div>
          <span class="fa-stack fa-3x">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-stack-1x fa-inverse three">3</i>
          </span>
        </div>
        <h2>
          Publish your application
        </h2>
        <p>
          Make your application available to anyone with a MyUSA account.
        </p>
        <p>
          <%= link_to "Learn More", authorizations_path, :target => "_new", :class => "btn btn-primary width-80" %>
        </p>
      </div>
    </div>
  </div>
  <div class="bg-gray top-border">
    <div class="container">
      <div class="row">
        <div class="col-sm-1 col-xs-offset-1 col-md-offset-1 col-lg-offset-2">
          <%= image_tag "myusa-shield@2x.png", :alt => 'MyUSA Shield Logo', :width => 58, :height => 70 %>
        </div>
        <div class="col-xs-offset-1 col-sm-9 col-sm-offset-0 col-md-8">
          <h1>
            A simple solution for agencies.
            <br/>
            A better experience for the American people.
          </h1>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/marketing/_for_people.html.erb
<section class="marketing" id="for-the-people">
  <div class="container">
    <div class="row">
      <!-- <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2"> -->
      <div class="col-md-12">
        <h1 class="text-center">
          Access your government services with one
          <br/>
          simple, reusable account
        </h1>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 hidden-sm hidden-md hidden-lg">
        <h2 class="text-center">
          Use your MyUSA account to access any of our partners.
        </h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4 col-md-4 text-center partner">
        <%= image_tag "partner-benefitsgov-nobg.png", :alt => 'Benefits.gov', :height => 50, :width => 199 %>
      </div>
      <div class="col-sm-4 col-md-4 text-center partner">
        <%= image_tag "partner-businessusa-nobg.png", :alt => 'Business USA', :height => 50, :width => 208 %>
      </div>
      <div class="col-sm-4 col-md-4 text-center partner">
        <%= image_tag "partner-usagov-nobg.png", :alt => 'USA.gov', :height => 50, :width => 126 %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 hidden-xs">
        <h2 class="text-center">
          Use your MyUSA account to access any of our partners.
        </h2>
      </div>
    </div>
  </div>
</section>