config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  
  get "redesign" => "redesign#index"

  root to: "home#index"
  get "legal" => "home#legal"
  get 'developer' => 'home#developer'
  post 'contact_us' => 'home#contact_us'

  # Legacy implementation used POST /oauth/authorize for both the user facing
  # authorization screen and the API endpoint to request a token ... so, we have
  # to support it. Set this route before the `use_doorkeeper` call so that this
  # route takes precedence over the other doorkeeper routes.
  post '/oauth/authorize' => 'doorkeeper/tokens#create', constraints: ->(req) {
    req.params['grant_type'] == 'authorization_code'
  }

  use_doorkeeper do
    skip_controllers :applications
    controllers authorizations: 'oauth/authorizations',
                authorized_applications: 'oauth/authorized_applications'
  end

  get 'authorizations' => 'oauth/authorized_applications#index'

  # Pull this out of the `use_doorkeeper` block so that we can put it at the
  # root level.
  # resources :applications, only: %w(new create show edit update destroy), as: 'oauth_applications'
  resources :applications, as: 'oauth_applications'

  post 'new_api_key' => 'applications#new_api_key'
  post 'make_public' => 'applications#make_public'

  devise_for :users,
    controllers: {
      omniauth_callbacks: "omniauth_callbacks" ,
      sessions: "sessions"
    }

  devise_scope :user do
    resource :user, only: [:update]
    get 'users/sign_in/:token_id' => 'sessions#show', as: 'user_session_token'

    namespace :users do
      namespace :factors do
        resource :sms
      end
    end
  end

  resource :mobile_recovery
  get 'mobile_recovery/cancel' => 'mobile_recoveries#cancel'
  get 'mobile_recovery/welcome' => 'mobile_recoveries#welcome'

  get 'settings/notifications' => 'notification_settings#index'
  post 'settings/notifications' => 'notification_settings#update'

  get 'unsubscribe/:delivery_method', to: 'unsubscribe#unsubscribe', as: 'unsubscribe'

  resource :profile, only: [:show, :edit, :additional, :update, :destroy] do
    get :additional
  end

  get 'settings/account_settings' => 'settings#account_settings'

  get 'admin' => 'admin#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1, as: 'v1' do
      resource :profile, only: [:show]
      resources :notifications, only: [:create]
      resources :tasks do
        resources :task_items
      end

      get 'tokeninfo', to: '/doorkeeper/token_info#show'
    end

    # For legacy reasons, we translate any API request without a version
    # in the path as a version 1 request.
    # e.g. `/api/STUFF` -> `/api/v1/STUFF`
    # Alas, I haven't found a better way of doing that translation than route
    # duplication. -- Yoz
    scope module: 'v1' do
      resource :profile, only: [:show]
      resources :notifications, only: [:create]
      resources :tasks do
        resources :task_items
      end
    end
  end

  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unprocessable_entity'
end

app/controllers/oauth/authorized_applications_controller.rb
class Oauth::AuthorizedApplicationsController < Doorkeeper::AuthorizedApplicationsController
  layout 'dashboard'

  helper :all

  def index
    @authorizations = current_user.authorizations.not_revoked
    @applications = current_user.oauth_applications
  end

  def destroy
    Doorkeeper::AccessToken.revoke_all_for params[:id], current_resource_owner
    redirect_to authorizations_path, notice: I18n.t(
      :notice, scope: [:doorkeeper, :flash, :authorized_applications, :destroy])
  end
end

app/views/doorkeeper/authorized_applications/_authorized_delete_form.html.erb
<%- submit_btn_css ||= 'btn btn-link no-padding no-border' %>
<%= form_tag oauth_authorized_application_path(application) do %>
  <input type="hidden" name="_method" value="delete">
  <%= submit_tag 'Revoke Access', onclick: "return confirm('Are you sure?')", class: submit_btn_css %>
<% end %>

app/views/doorkeeper/authorized_applications/_authorized_scope_list.html.erb
<ul class="list-unstyled scope-list">
  <% scopes_by_group(scopes) do |group, group_scopes| %>
    <%- if group_scopes.present? -%>
    <li>
      <h2 class="open"><%= t("scope_groups.#{group}.description") %></h2>
      <div class="form-group">
        <h3><%= t("scope_groups.#{group}.subheading") %></h3>
        <% group_scopes.each do |scope| %>
          <div class="row">
            <%- if profile_scope?(scope) -%>
              <div class="col-md-3">
                <%= scope_label(scope) %>
              </div>
              <div class="col-md-9">
                <label><%= scope_field_tag(scope, read_only: true) %></label>
              </div>
            <%- end -%>
          </div>
        <% end %>
      </div>
    </li>
    <%- end -%>
  <% end %>
</ul>

app/views/doorkeeper/authorized_applications/_delete_form.html.erb
<%- submit_btn_css ||= 'btn btn-link' %>
<%= form_tag [:oauth, application] do %>
  <input type="hidden" name="_method" value="delete">
  <%= submit_tag 'Delete Application', onclick: "return confirm('Are you sure?')", class: submit_btn_css %>
<% end %>

app/views/doorkeeper/authorized_applications/_scope_list.html.erb
<ul class="list-unstyled scope-list">
  <% scopes_by_group(scopes) do |group, scopes| %>
    <li>
      <h2 class="open"><%= t("scope_groups.#{group}.description") %></h2>
      <div class="form-group">
        <h3><%= t("scope_groups.#{group}.subheading") %></h3>
        <% scopes.each do |scope| %>
          <div class="row top-buffer">
            <div class="col-md-3">
              <%= scope_label(scope) %>
            </div>
            <div class="col-md-9">
            </div>
          </div>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/doorkeeper/authorized_applications/index.html.erb
<div class="row aglio app-settings">
  <div class="col-md-3">
    <%= render 'profiles/nav'%>
  </div>
  <div class="col-md-9">
    <h1>
      My Applications
      <div class="pull-right">
        <%= link_to 'Create Application', new_oauth_application_path, class: 'btn btn-success' %>
      </div>
    </h1>
    <% if !@applications.empty? %>
      <h2>
        Developer applications
      </h2>

      <table class="table table-striped">
        <thead>
        <tr>
          <th>Name</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <% if @applications.blank? %>
          <tr>
            <td colspan="3">
              You do not have any applications.
            </td>
          </tr>
        <% end %>
        <% @applications.each do |application| %>
          <tr id="application_<%= application.id %>">
            <td><%= link_to application.name, edit_oauth_application_path(application) %></td>
            <td><%= app_status(application) %></td>
            <td>
              <%= form_tag new_api_key_path, method: :post do %>
                <%= hidden_field_tag(:id, application.id) %>
                <%= submit_tag 'New API Key',
                  onclick: "return confirm('Are you sure you want to generate a new client secret key?')",
                  class: 'btn btn-link' %>
              <% end %>
              <%= link_to 'Edit Application', edit_oauth_application_path(application), class: 'btn btn-link' %>
              <% if !application.public && application.requested_public_at.nil? %>
                <%= form_tag make_public_path, method: :post do %>
                  <%= hidden_field_tag(:id, application.id) %>
                  <%= submit_tag 'Request Public Access', class: 'btn btn-link' %>
                <% end %>
              <% end %>
              <%= render 'delete_form', application: application %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>

    <h2>Authorized Applications</h2>

      <div class="row scope-page">
        <div class="col-md-12">
          <%- if @authorizations.blank? -%>
            <p><%= t('no_authorizations') %></p>
          <%- else -%>
            <% @authorizations.each do |authorization| %>
              <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="panel-title"><%= authorization.application.name %></span>
                    <br/>
                    <span class="panel-subtitle">Granted: <%= authorization.created_at.strftime('%m/%d/%Y') %></span>
                    <div class="pull-right text-right">
                      <%= render 'authorized_delete_form', application: authorization.application %>
                    </div>
                </div>
                <div class="panel-body">
                  <h1>Permissions</h1>
                  <%= render 'authorized_scope_list', scopes: authorization.scopes %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

  </div>
</div>